default:
	dot arduino.dot -Tps   -o arduino.ps
	dot arduino.dot -Tpng  -o arduino.png
	dot python.dot  -Tps   -o python.ps
	dot python.dot  -Tpng  -o python.png
	dot struct.dot  -Tps   -o struct.ps
	dot struct.dot  -Tpng  -o struct.png
